<?php

/**
 * Implementation of hook_init().
 */
function os_admin_init() {
  if (user_is_logged_in()) {
    drupal_add_css(drupal_get_path('module', 'os_admin') .'/os-admin.css');
  }
}


/**
 * Implementation of hook_menu().
 */
function os_admin_menu() {
  $items['admin/os_admin_product_add'] = array(
    'title' => 'Create Product',
    'description' => 'Easy shortcut to create a product.',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/product'),
    'access arguments' => array('create product content'),
    'weight' => -10,
  );

  return $items;
}
